#-------------------------------
# General Site Settings
title: ê·œëµì˜ ëª…í•œ ê¸°ìˆ ë¸”ë¡œê·¸
logo: logo.svg # You can add own logo.
description: ì´ê±° ëª…í•˜ê±°ë“ ìš”...


#-------------------------------
# Author Settings
author:
  name: Gyumyung Lee
  image: hero.jpg
  say-hello: Hello, Iâ€™m <strong>Gyumyung Lee</strong>ğŸ‘‹
  bio: Backend Programmer, <strong>Spring Boot</strong>, <strong>Java</strong>, <strong>Kotlin</strong>. and I consider it important to <strong>record</strong>. Such as <a href="https://github.com/lgm1007/TIL" target="blank">TIL</a> and Blog.


#-------------------------------
# Contact links
github: https://github.com/lgm1007/ # Add your Twitter handle
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
